id: P2D9F6638
initial_creation_type: input
source_metadata:
  title: Dilgo Khyentse Rinpoche Series
  language: nl
  description: 'Texts by and about Kyabje Dilgo Khyentse Rinpoche, Tashi Paljor (dil
    mgo mkhyen brtse bkra shis dpal ''byor, 1910-1991):'
  volume:
    679f530ccbed4dc18d00c79168254e07:
      title: Advice to Three-Year Retreatants
      parent: Advice
    5e672b006c134bb8bd7fd1eefa5813f8:
      title: Heart Advice in Four Lines
      parent: Advice
    0cc475abcf064446b203d555d0e3f242:
      title: Letter of Advice to Jamyang Gyaltsen
      parent: Advice
    54f770b525be40d498788e141664bb07:
      title: A Prayer for the Spread of Kyabje Dilgo Khyentse Rinpoche’s Termas
      parent: Aspiration Prayers
    77b068380db24ed49d811c778d611fe4:
      title: 'The Blissful Path to the Ocean of Bodhichitta: A Brief Prayer of Aspiration
        for Mind Training'
      parent: Aspiration Prayers
    bf66bea61cd14cd1823c7e5475c2b9b9:
      title: 'The Vidyādharas'' Words of Truth: An Aspiration Connected with the Stages
        of the Path of the Three Roots, from the Heart Essence of the Vast Expanse'
      parent: Aspiration Prayers
    c14cb1c510bf4e4686e67d3882647011:
      title: 'Wisdom''s Melody: An Aspiration to Realize Madhyamaka, Mahāmudrā, and
        Mahā Ati'
      parent: Aspiration Prayers
    bd7cd02ba5dc4c2dabb2fce58045b456:
      title: 'Wondrous Light of Lunar Nectar: The Biography of Chatral Kunga Palden,
        a Yogin of the Supreme Vehicle'
      parent: Biographies
    ac2a3ab992af4c11b27f3a76a1bd7fa5:
      title: Calling the Guru From Afar
      parent: Calling the Guru from Afar
    f2492281ba2c491885687ca716d25475:
      title: Calling the Guru from Afar
      parent: Calling the Guru from Afar
    143c500e387643c280d49d4e2fecc29b:
      title: 'Nectar Shower of Blessings: A Song of Yearning Devotion Recalling the
        Everpresent Gurus'
      parent: Calling the Guru from Afar
    55ff539b84ad42fbad925e750c448e02:
      title: 'Repository of Every Form of Dharma That Might Be Wished For: A Catalogue
        to the Published Miscellaneous Writings of the Venerable Guru Jamyang Chökyi
        Lodrö'
      parent: Catalogues
    3ff86cffafc841749d80f58fc936cefb:
      title: Concise Offering of the Body from the Root Text of the Heart Accomplishment
        of the Guru Tukdrup, The Essential Manual of Oral Instructions (Shaldam Nyingjang)
      parent: Chöd
    bde769c70c444c999651749534b12d30:
      title: 'The Sage who Dispels Mind’s Anguish: Advice from the Guru, the Gentle
        Protector Mañjuśrī on the Means of Accomplishing the Yogas of Śamatha and
        Vipaśyanā'
      parent: Commentaries
    d0cfe5844650497eaeba804c121b56a5:
      title: 'Shower of Indestructible Splendour: A Self-Initiation for the Guru Practice
        of the Vidyādhara Assembly, from the Heart-Essence of the Vast Expanse'
      parent: Empowerment Rites
    913dc5046e9a453abb2fa7293cbdaac2:
      title: 'A Garland of Vajra Words: A Prayer to the Guru'
      parent: Guru Rinpoche Prayers
    2323c20c9fd44bd6a08c89e627d66e82:
      title: 'All Wishes Swiftly Fulfilled: A Prayer to the Mahāguru of Uḍḍiyāna in
        Eight Chapters'
      parent: Guru Rinpoche Prayers
    943ecb648f22492fb5b3e4519e3fe829:
      title: Guru Yoga – A Rang Rig Ma Chö
      parent: Guru Yoga
    e9862c37d6bf4ea894e8dab092039cfb:
      title: 'Guru Yoga: The Complete Path of Sūtra And Tantra'
      parent: Guru Yoga
    bf9ed458e5ee441cad4397e788b6796a:
      title: 'The Quintessence of the Profound Path: A Concise Guide to the Stages
        of Visualization for the Guru Yoga of the Seven-Line Supplication, A Shower
        of Blessings'
      parent: Guru Yoga
    095537f585d946d883cead537952db97:
      title: 'The Sun of Ambrosial Wisdom: A Guru Yoga of Dharmarāja Sakya Paṇḍita'
      parent: Guru Yoga
    a7077aaaaf794adab1c201299ea15b97:
      title: A History of Dzongsar Monastery
      parent: History
    2e373cd0bde1401987eca77abb84acb1:
      title: 'Beautiful Clouds of Blessings: A Prayer to the Lineage Masters of the
        Heart Essence of the Vast Expanse from the Great Perfection'
      parent: Lineage Prayers
    8b0c49a5265849b29183e9b36f0296a4:
      title: Prayer to Longchenpa (Adapted from the Words of Mipham Rinpoche)
      parent: Lineage Prayers
    28463251153d4ebba833589ccad889d6:
      title: Supplication to the Lineage of the Heart Essence of the Vast Expanse
      parent: Lineage Prayers
    5656037763eb4f409beb34f9c36ddf07:
      title: 'Vajrakīla Prayer: A Rain of Accomplishments'
      parent: Lineage Prayers
    17e31e9e01e74417a2e17caaf7253239:
      title: Ambrosia for the Mind
      parent: Lojong
    198c1f2977ed4282be31904ace82c4db:
      title: Prayer for the Long Life of Dzongsar Jamyang Khyentse Rinpoche
      parent: Long Life Prayers
    d9cd6eb4b87a43b9ad9c4fc82c1f1399:
      title: Prayer for the Long Life of Shechen Rabjam Rinpoche
      parent: Long Life Prayers
    03d767f714f14599966a48c74a9bc8e3:
      title: 'The Vajra Sitar of Immortality: A Prayer for the Long Life of the Fourth
        Incarnation of Terchen Chokgyur Lingpa'
      parent: Long Life Prayers
    f035a93f398c49bd85a4db86e88c5d92:
      title: 'True Words to Accomplish Immortality: A Longevity Prayer to the Tulku
        of Jamyang Khyentse, Thupten Chökyi Gyatso'
      parent: Long Life Prayers
    6fd9d0cbe3c843dfb0c48593e776ad35:
      title: A Prayer to Dilgo Khyentse Rinpoche
      parent: Prayers
    39a76522d5454dd59948f816ae79ac9a:
      title: A Prayer to Kyabje Dilgo Khyentse Rinpoche
      parent: Prayers
    57ad73f821d64dc5a212b38c64dc08d8:
      title: Invocation of the Vidyādhara Gurus
      parent: Prayers
    516fcaeae9fb4de9ba1fe0790795319a:
      title: 'Light of Compassion: A Prayer to the Wisdom Ḍākinīs'
      parent: Prayers
    eeb7ce1ae08b43858742f4c7f33719c7:
      title: Prayer for the Fulfilment of Aspirations
      parent: Prayers
    e727161d341f4dd8b28ef2fcfb992dc4:
      title: Prayer to Khandro Tsering Chödrön
      parent: Prayers
    601dc740fed24acc896542da1823b454:
      title: 'The Lotus of Faith: A Supplication to the Successive Lives of Shechen
        Rabjam'
      parent: Prayers
    8c4cb5cd117e4fdeafa19eaba8e1e92a:
      title: 'The Potent Nectar of Accomplishment: A Prayer and Supplication to the
        Vidyādhara Gurus of the Three Lineages'
      parent: Prayers
    af8848a8a600491a8c3714146ebfcc80:
      title: The Prayer to Swiftly Fulfil All Wishes
      parent: Prayers
    c4cbce010af449828051c2b868c4fa73:
      title: 'The Precious Jewel Essence: A Prayer of the Four Dharmas'
      parent: Prayers
    f715bc917db241698dcd371eaeb30bb1:
      title: 'The Quintessence of Marvellous Nectar: A Prayer Based on the Liberational
        Life of the Gentle Protector Guru'
      parent: Prayers
    d1711e73b2e74a198c87f6b76af2db96:
      title: 'The Swift Bestowal of Blessings: A Prayer to the Glorious Protector
        Guru'
      parent: Prayers
    caa45fe00c6545e9871bba95e73fa8c9:
      title: A Sādhana of Golden Mañjughoṣa
      parent: Sādhanas
    fc71b09b40684fc2befc4cb503dd9f7b:
      title: A Sādhana of Tārā Sarasvatī
      parent: Sādhanas
    d1b2ef26b7d5482fb9b5d6e4ab8a1722:
      title: Concise Daily Practice of Vajrasattva
      parent: Sādhanas
    3d75c1762151441197cb7403632e3d8b:
      title: Daily Practice of Guru Rinpoche, Buddha of Medicine
      parent: Sādhanas
    750f50db5f2c41a59054da6de742071a:
      title: 'The Refined Essence of Compassion: A Daily Sādhana for the Natural Liberation
        of Suffering, the Secret Practice of the Great Compassionate One'
      parent: Sādhanas
    c052338d4947449bb59ad8f5b8f047ce:
      title: Lamenting Prayer to Jamyang Chökyi Lodrö
      parent: Swift Rebirth Prayers
    6b591d2ffcb24eeab49a51cd8be872de:
      title: 'Bestowing the Glory of Wisdom: A Gaṇacakra Feast for Nyingtik Saldrön'
      parent: Tsok Offering
created_at: '2022-02-28T22:53:20.381573'
last_modified_at: '2022-02-28T22:53:20.381575'
